version: "3"
services:
  app:
    build: ./app
    volumes:
      - /home/unroot/Development/projects/mevn-docker/app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    command: npm run start
  api:
    build: ./api
    volumes:
      - /home/unroot/Development/projects/mevn-docker/api:/usr/src/api
      - /usr/src/api/node_modules
    ports:
      - "3000:3000"
    links:
      - database
    command: npm run start
  database:
    image: mongo
    ports:
      - "27017:27017"